### ISSUE TITLE
release modules without configure/RELEASE

### ISSUE THREAD

**Issue by arvinderpalaha** [ulrikpedersen/dls_ade#2]
The gitolite dls_release repository has been updated to allow releasing ioc and support modules that do not have a configure/RELEASE file.

It was thought that everything in ioc or support would be epics, and so would need such a file to build, everything else either being a tool or other module. But enough people made use of the previous version allowing builds without configure/RELEASE files to develop software in ioc or support areas, and would like this functionality back.

Could you please incorporate the changes I have made into where dls-release.py is now residing? The tag/version with the changes I have made is 2-4-3.

**Comment by ulrikpedersen** [comment]
Hi Arvinder.
Please can you issue this ticket to dls-controls/dls_ade instead. That is where Martin and Gary are working on this...
Thanks!
ulrik

**Comment by arvinderpalaha** [comment]
Woops, will do :)
